apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-function-public
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: java-function-public
  namespace: backend
spec:
  source:
    git:
      url: https://github.com/fabianbrash/java-function-public.git
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: functions.Handler